# Copyright (c) 2020-2022 TU Delft & Valentijn van de Beek <v.d.vandebeek@student.tudelft.nl> All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

site_name: BAAS Project Documentation
site_url: https://docs.baas-project.nl/
repo_url: https://github.com/baas-project/baas
site_description: Documentation for the BAAS imaging software.
site_author: TU Delft & Valentijn van de Beek
copyright: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
strict: true

nav:
    - Home: index.md
    - General:
        - Overview: general/index.md
        - Image layout: general/images.md
        - Architecture: general/architecture.md
        - Project Structure: general/project_structure.md
    - Control Server:
        - Overview: control_server/index.md
        - Logging in: control_server/logging_in.md
        - Running the server: control_server/running_baas_control_server.md
        - REST API: control_server/REST API.md
    - Management OS:
        - Overview: management_os/index.md
        - Reprovision flow: management_os/reprovision_flow.md

theme: readthedocs
#  name: material

plugins:
  - search
  - mkdocs-nav-enhancements
  - section-index
  - spellcheck:
      ignore_code: yes
      min_length: 4
      max_capital: 4
      allow_unicode: yes
      known_words: known_words.txt

#  - with-pdf


markdown_extensions:
  - toc
  - smarty
  - sane_lists
  - admonition
  - wikilinks
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml  # PlantUML server, for remote rendering
